BATCH_SIZE = 128  # Some hyper-parameters to adjust!
GRAPHMAXCOORDINATE = 100
NUMBER_OF_VEHICLES = 20  # Change AidoGuest.py as well!
MAP_DIVIDE = 5


# Vehicle Status
STAY = 0
DRIVETOCUSTOMER = 1
DRIVEWITHCUSTOMER = 2
REBALANCE = 3

MID_POINTS = [[GRAPHMAXCOORDINATE/MAP_DIVIDE/2 + GRAPHMAXCOORDINATE/MAP_DIVIDE * (n % MAP_DIVIDE),
               GRAPHMAXCOORDINATE/MAP_DIVIDE/2 + GRAPHMAXCOORDINATE/MAP_DIVIDE * (n // MAP_DIVIDE)] for n in range(MAP_DIVIDE ** 2)]